Task01/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('financialApp/', include('financialApp.urls')),
    path('admin/', admin.site.urls),
]

financialApp/urls.py
from django.urls import path

from . import views

app_name = 'financialApp'
urlpatterns = [
    path('users/', views.user_index, name='user_index'),
    path('users/<int:user_id>/', views.user_detail, name='user_detail'),
    path('transactions/', views.transaction_index, name='transaction_index'),
#    path('users/<int:user_id>/user_transaction_filtered', views.user_transaction_filtered, name='user_transaction_filtered')
]

financialApp/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    def __str__(self):
        return self.first_name + ' '+self.last_name

class Transaction(models.Model):
    date = models.DateField('time of transaction')
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    amount = models.DecimalField(decimal_places=10, max_digits=20)
    def __str__(self):
        return 'User: '+ self.user.first_name+' '+self.user.last_name +', amount: '+str(self.amount) + ' , date: ' + str(self.date)

financialApp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Transaction, User
from django.views import generic
from django.urls import reverse
import datetime
import json


def user_index(request):
    if(request.method == 'POST'):
        sort = request.POST.get('sort')
        name_substring = request.POST.get('name_text') # check wheather first or last name contains given string
        u = User.objects.filter(first_name__icontains=name_substring).union(
            User.objects.filter(last_name__icontains=name_substring))
        if(sort == 'first_name'): # if needs to be sorted by first_name
            u = u.order_by('-first_name')
        elif(sort == 'last_name'):
            u = u.order_by('-last_name')
    else:
        u = User.objects.all()
    return render(request, 'financialApp/user_index.html', {'user_list':u} )



def user_detail(request, user_id):
    u = User.objects.get(id=user_id)
    t = None
    if request.method == 'POST':
        t = u.transaction_set.filter(date__range=[request.POST.get('start'), request.POST.get('end')])
        if request.POST.get('group')=='on': # if grouping is on, then we make a dict of dates -> sum amounts
            dict = {}
            for transaction in t.iterator():
                if transaction.date in dict:
                    dict[str(transaction.date)] = dict[str(transaction.date)] + float(transaction.amount);
                else:
                    dict[str(transaction.date)] = float(transaction.amount);
            json_string = json.dumps(dict) # create json from dict
            return render(request, 'financialApp/user_detail.html', {
                'user': u, 'transactions': t, 'grouped_amounts_json': json_string
                })
        else: # grouping is off, no json
            t = u.transaction_set.filter(date__range=[request.POST.get('start'), request.POST.get('end')])
            return render(request, 'financialApp/user_detail.html', {
                'user': u, 'transactions': t
                })
    else: # this is get, then return all transactions for this user
        t = u.transaction_set.all()
        return render(request, 'financialApp/user_detail.html',
            {'user' : u, 'transactions': t} )

def transaction_index(request):
    if(request.method == 'POST'):
        income_outcome = request.POST.get('income_outcome')
        sort = request.POST.get('sort')
        if(income_outcome=='income'): # check if user needs only income or outcome transactions
            transaction_list = Transaction.objects.filter(amount__gte=0).filter(date__range=
            [request.POST.get('start'), request.POST.get('end')])
        elif(income_outcome=='outcome'):
            transaction_list = Transaction.objects.filter(amount__lte=0).filter(date__range=
            [request.POST.get('start'), request.POST.get('end')])
        else:
            transaction_list = Transaction.objects.filter(date__range=
                        [request.POST.get('start'), request.POST.get('end')])
        if(sort == 'amount'): # check if transactions need to be sorted
            transaction_list = transaction_list.order_by('-amount')
        elif(sort == 'date'):
            transaction_list = transaction_list.order_by('-date')
    else:
        transaction_list = Transaction.objects.all()
    return render(request, 'financialApp/transaction_index.html', {'transaction_list' : transaction_list})

financialApp/templates/financialApp/transaction_index.html
{% if transaction_list %}
    <table summary="Transaction list">
    <tr><th>Amount</th><th>Date</th>
	{% for transaction in transaction_list %}
	      <tr><td>{{transaction.amount}}</td><td>{{transaction.date}}</td></tr>
	{% endfor %}
    </table>
{% else %}
    <p>No transactions are available.</p>
{% endif %}
<form action="{% url 'financialApp:transaction_index'%}" method="post">
  {% csrf_token %}
  <p><label for="selected_date1">From:</label> <input type="date" name="start" value="2020-01-01"></p>
  <p><label for="selected_date2">To:</label> <input type="date" name="end" value="2020-01-01"></p>
  Show only: <select name="income_outcome" class="filter-selectbox">
  <option value="income">Income</option>
  <option value="outcome">Outcome</option>
  <option value="both">Both</option></select>
  <p>
  Sort by:
  <div>
  <input type="radio" name="sort" id="date" value="date">
    <label for="date">Date</label>
  <input type="radio" name="sort" id="amount" value="amount">
      <label for="amount">Amount</label>
      <input type="radio" name="sort" id="none" value="none" checked="True">
          <label for="none">None</label>
  </div>
  </p>
  <input type="submit" value="Submit">
</form>

financialApp/templates/financialApp/user_detail.html
<h1>{{user.first_name}} {{user.last_name}}</h1>
<body>
{% if transactions%}
<table summary="Transactions">
  <tr><th>Amount</th><th>Date</th>
	 {% for transaction in transactions %}
     <tr><td>{{transaction.amount}}</td><td>{{transaction.date}}</td></tr>
	  {% endfor %}
</table>
{% else %}
    <p>No transactions are available.</p>
{% endif %}
<form action="{% url 'financialApp:user_detail' user.id %}" method="post">
  {% csrf_token %}
  <p><label for="selected_date1">From:</label> <input type="date" name="start" value="2020-01-01"></p>
  <p><label for="selected_date2">To:</label> <input type="date" name="end" value="2020-01-01"></p>
  <label for="repeat">Send grouped by dates JSON?</label>
  <input id="grp" name="group" type="checkbox" >
  <input type="submit" value="Submit">
</form>
{% if grouped_amounts_json %}
<script>
    var jsonObject = JSON.parse('{{ grouped_amounts_json | escapejs }}');
</script>
{% endif %}

</body>
</html>

financialApp/templates/financialApp/user_index.html
{% if user_list %}
    <ul>
	{% for user in user_list %}
     <li>
	      <a href="{% url 'financialApp:user_detail' user.id %}">{{user.first_name}} {{user.last_name}}</a>
		</li>
	{% endfor %}
    </ul>
{% else %}
    <p>No users are available.</p>
{% endif %}
<form action="{% url 'financialApp:user_index'%}" method="post">
  {% csrf_token %}
  <p><label for="name_text">Name:</label> <input type="text" name="name_text"></p>
  <p>
  Sort by:
  <div>
  <input type="radio" name="sort" id="first_name" value="first_name">
    <label for="date">First name</label>
  <input type="radio" name="sort" id="last_name" value="last_name">
      <label for="amount">Last name</label>
      <input type="radio" name="sort" id="none" value="none" checked="True">
          <label for="none">None</label>
  </div>
  </p>
  <input type="submit" value="Submit">
</form>